#!/usr/bin/env perl
use autodie qw(open sysseek sysread truncate);

my $file = shift;
open my $fh, '+>>', $file;
my $pos = tell $fh;
$pos > 0 or exit;
my $len = ($pos >= 2 ? 2 : 1);
sysseek $fh, $pos - $len, 0;
sysread $fh, $buf, $len or die 'No data to read?';

if ($buf eq "\r\n") {
    # print "truncate DOS-style CR-LF\n";
    truncate $fh, $pos - 2;
} elsif(substr($buf, -1) eq "\n") {
    # print "truncate Unix-style LF\n";
    truncate $fh, $pos - 1;
} elsif(substr($buf, -1) eq "\r") {
    # print "truncate Mac-style CR\n";
    truncate $fh, $pos - 1;
}
